### PR TITLE
fix: change OpenSearchStatusException check to OpenSearchException to include more client side error type

### LINKED ISSUE #4724: [BUG] Create memory session when session is disabled return 500 instead of 400
**What is the bug?**
Currently if we create a session disabled memory container and use create agentic memory session api to create a agentic memory session it will return 500 internal server error instead of bad request.

**What is the expected behavior?**
It should return 400 BAD_REQUEST

**What is your host/environment?**
 - OS: 3.5

### PR DESCRIPTION
**Pull request by b4sjoo**
#### Summary
Updates error handling to use `OpenSearchException` instead of `OpenSearchStatusException` when preserving 4XX client errors. This covers more client-side error types (e.g. `IndexNotFoundException`, `ResourceNotFoundException`) and avoids masking them as internal server errors.

#### Changes
1. Error handling (`OpenSearchStatusException` → `OpenSearchException`)
* `MemoryProcessingService` – Replaced `OpenSearchStatusException` checks with `OpenSearchException` in 4 error paths (fact extraction, decision extraction, summary generation).
* `TransportAddMemoriesAction` – Same change in 3 error handlers.
* `TransportCreateSessionAction` – Added 4XX preservation in the indexData error handler.
* `MLPredictTaskRunner` – Updated 4XX check when deciding whether to track errors.
2. `TransportCreateSessionAction` – Session disabled check
* Returns `BAD_REQUEST` with message "Session is disabled for this container" when `container.getConfiguration().isDisableSession()` is `true`.
* Fails fast before indexing when sessions are disabled.

#### Rationale
`OpenSearchStatusException` is a subclass of `OpenSearchException`. Exceptions such as `IndexNotFoundException` and `ResourceNotFoundException` extend `OpenSearchException` but not `OpenSearchStatusException`, so they were previously turned into generic 500 errors. Checking for `OpenSearchException` ensures all 4XX client errors are preserved and returned to the client with the correct status and message.

#### Testing
New unit tests added for TransportCreateSessionAction.
All existing tests pass.
Now create session calls in the memory container where `disableSession` is `true` will return a 400

```
# Request
POST /_plugins/_ml/memory_containers/{{container_id}}/memories/sessions

# Response with BAD_REQUEST
{
    "error": {
        "root_cause": [
            {
                "type": "status_exception",
                "reason": "Session is disabled for this container"
            }
        ],
        "type": "status_exception",
        "reason": "Session is disabled for this container"
    },
    "status": 400
}
```

### Related Issues
Resolves #4724

### Check List
- [ ] New functionality includes testing.
- [ ] New functionality has been documented.
- [ ] API changes companion pull request [created](https://github.com/opensearch-project/opensearch-api-specification/blob/main/DEVELOPER_GUIDE.md).
- [ ] Commits are signed per the DCO using `--signoff`.
- [ ] Public documentation issue/PR [created](https://github.com/opensearch-project/documentation-website/issues/new/choose).

By submitting this pull request, I confirm that my contribution is made under the terms of the Apache 2.0 license.
For more information on following Developer Certificate of Origin and signing off your commits, please check [here](https://github.com/opensearch-project/ml-commons/blob/main/CONTRIBUTING.md#developer-certificate-of-origin).

### CODE REVIEW

**Comment by dhrubo-os** [comment]
I didn't clearly understand how is that really helping here?

**Comment by b4sjoo** [comment]
> I didn't clearly understand how is that really helping here?

Check OpenSearch Repo, you will find `ResourceNotFoundException` is `OpenSearchException` instead of `OpenSearchStatusException`, that's why previously in many cases it is not caught correctly and converted into a 500 `InternalServerError`
https://github.com/opensearch-project/OpenSearch/blob/main/server/src/main/java/org/opensearch/ResourceNotFoundException.java

**Comment by b4sjoo** [comment]
In the meantime in my opinion in the future all `MLResourceNotFoundException` should be converted to OpenSearch `ResourceNotFoundException` because current `MLResourceNotFoundException` is not set a RestStatus code with `404`

**Comment by b4sjoo** [comment]
> OpenSearchException is the base class for many exceptions including server-side
> errors. Some subclasses of OpenSearchException may not have a meaningful HTTP status
> and could return unexpected values. Additionally, OpenSearchStatusException is
> already a subclass of OpenSearchException, so the change is correct in scope, but
> you should verify that all OpenSearchException subclasses reliably implement
> status() to avoid NullPointerException when calling
> osException.status().getStatus().

Checked [OpenSearchException](https://github.com/opensearch-project/OpenSearch/blob/f46ce23c24b53fd98dcfd9c4fce0a41cb565cda3/libs/core/src/main/java/org/opensearch/OpenSearchException.java#L304), by default it will be 500, so it's not nullable.

> OpenSearchException.status() can potentially return null for certain subclasses,
> which would cause a NullPointerException when calling status.getStatus(). A null
> check should be added before dereferencing the status object.

Same.

File: plugin/src/main/java/org/opensearch/ml/action/memorycontainer/memory/MemoryProcessingService.java [hunk 1]
```diff
@@ -186,8 +187,8 @@ public void extractFactsFromConversation(
                 listener.onResponse(facts);
             } catch (Exception e) {
                 // Preserve client errors (4XX) with their detailed messages
-                if (e instanceof OpenSearchStatusException) {
-                    OpenSearchStatusException osException = (OpenSearchStatusException) e;
+                if (e instanceof OpenSearchException) {
```
Comment (ylwu-amzn) [inline plugin/src/main/java/org/opensearch/ml/action/memorycontainer/memory/MemoryProcessingService.java:190]: This same 4XX-preservation pattern now appears **7+ times** across `MemoryProcessingService`, `TransportAddMemoriesAction`, and `TransportCreateSessionAction`:

```java
if (e instanceof OpenSearchException) {
    OpenSearchException osException = (OpenSearchException) e;
    if (osException.status().getStatus() >= 400 && osException.status().getStatus() < 500) {
        listener.onFailure(e);
        return;
    }
}
```

Consider extracting to a utility method (e.g., `isClientError(Exception e)`) to reduce duplication and ensure future error handlers stay consistent. `AgentUtils.extractStatusCode` already does something similar.

File: plugin/src/main/java/org/opensearch/ml/task/MLPredictTaskRunner.java [hunk 2]
```diff
@@ -740,8 +740,8 @@ boolean shouldTrackRemoteFailure(Exception e) {
         }
 
         // Don't track any 4xx client errors (user/configuration issues)
-        if (e instanceof OpenSearchStatusException) {
-            RestStatus status = ((OpenSearchStatusException) e).status();
+        if (e instanceof OpenSearchException) {
```
Comment (ylwu-amzn) [inline plugin/src/main/java/org/opensearch/ml/task/MLPredictTaskRunner.java:743]: Note: `MLInferenceSearchResponseProcessor.java:232` has the same `instanceof OpenSearchStatusException` pattern for 4XX checks but is not updated in this PR. Should it be included for consistency, or is that intentionally out of scope?

File: plugin/src/main/java/org/opensearch/ml/action/session/TransportCreateSessionAction.java [hunk 3]
```diff
@@ -98,6 +99,10 @@ protected void doExecute(Task task, MLCreateSessionRequest request, ActionListen
                     );
                 return;
             }
+            if (container.getConfiguration().isDisableSession()) {
```
Comment (ylwu-amzn) [inline plugin/src/main/java/org/opensearch/ml/action/session/TransportCreateSessionAction.java:102]: Clean fail-fast. Good that this returns before `createNewSession` to avoid unnecessary work.

File: plugin/src/test/java/org/opensearch/ml/action/session/TransportCreateSessionActionTests.java [hunk 4]
```diff
@@ -349,6 +352,99 @@ public void testDoExecute_AccessDenied() {
...
+            return null;
+        }).when(memoryContainerHelper).indexData(any(), any(), any());
+
+        // Execute
+        transportCreateSessionAction.doExecute(task, request, actionListener);
+
+        // Verify - 4XX errors are preserved and passed through (not converted to INTERNAL_SERVER_ERROR)
+        ArgumentCaptor<Exception> exceptionCaptor = ArgumentCaptor.forClass(Exception.class);
+        verify(actionListener).onFailure(exceptionCaptor.capture());
+
```
Comment (ylwu-amzn) [inline plugin/src/test/java/org/opensearch/ml/action/session/TransportCreateSessionActionTests.java:432]: Good test — this specifically uses `IndexNotFoundException` which extends `OpenSearchException` but NOT `OpenSearchStatusException`, directly validating the fix. The assertion pattern with the type check and status extraction is thorough.

File: plugin/src/main/java/org/opensearch/ml/action/memorycontainer/memory/MemoryProcessingService.java [hunk 5]
```diff
@@ -435,8 +436,8 @@ private List<MemoryDecision> parseMemoryDecisions(String llmResultPath, MLTaskRe
             }
         } catch (Exception e) {
             // Preserve client errors (4XX) with their detailed messages
```
Comment (dhrubo-os) [inline plugin/src/main/java/org/opensearch/ml/action/memorycontainer/memory/MemoryProcessingService.java:438]: The current pattern preserves client errors but wraps all 5XX in a generic "Internal server error", which loses the original status code and message.

Could you please remind me again why we wanted this in the first place? Is this due to security concern?

File: plugin/src/main/java/org/opensearch/ml/action/memorycontainer/memory/MemoryProcessingService.java (hunk 1 above)
Comment (dhrubo-os) [reply plugin/src/main/java/org/opensearch/ml/action/memorycontainer/memory/MemoryProcessingService.java:190]: +1 on this nit

File: plugin/src/main/java/org/opensearch/ml/action/memorycontainer/memory/MemoryProcessingService.java (hunk 5 above)
Comment (b4sjoo) [reply plugin/src/main/java/org/opensearch/ml/action/memorycontainer/memory/MemoryProcessingService.java:438]: Yes, it is due to security concern.

File: plugin/src/main/java/org/opensearch/ml/task/MLPredictTaskRunner.java (hunk 2 above)
Comment (b4sjoo) [reply plugin/src/main/java/org/opensearch/ml/task/MLPredictTaskRunner.java:743]: Intentionally out of scope because it is not wrapping 500 error message.

File: plugin/src/main/java/org/opensearch/ml/action/memorycontainer/memory/MemoryProcessingService.java (hunk 5 above)
Comment (dhrubo-os) [reply plugin/src/main/java/org/opensearch/ml/action/memorycontainer/memory/MemoryProcessingService.java:438]: What was the security concern?

Comment (b4sjoo) [reply plugin/src/main/java/org/opensearch/ml/action/memorycontainer/memory/MemoryProcessingService.java:438]: By security team they found the error stack trace for 5xx can reveal the internal logic
