### PR TITLE
Fixes Two Flaky IT classes RestMLGuardrailsIT & ToolIntegrationWithLLMTest

### LINKED ISSUE #3237: [BUG]-(flaky tests) ITs involving models have race conditions
**What is the bug?**
There are failures on ITs that depend on a creating a model. This usually involves creating a model (`Failed to find model`) and when the model tries to be deleted but it can't because the model is in deploying or deployed state (`Model cannot be deleted in deploying or deployed state. Try undeploy model first then delete`).
 
**How can one reproduce the bug?**
```
./gradlew ':opensearch-ml-plugin:integTest' --tests "org.opensearch.ml.tools.VisualizationsToolIT.testVisualizationFound" -Dtests.seed=4E5188680CFAD2E9 -Dtests.security.manager=false -Dtests.locale=fr-ML -Dtests.timezone=Africa/Mbabane -Druntime.java=21

VisualizationsToolIT > testVisualizationFound FAILED
    org.opensearch.client.ResponseException: method [DELETE], host [http://[::1]:35467], URI [/_plugins/_ml/models/p7RlYZMB7jpbSjye2g3j], status line [HTTP/1.1 400 Bad Request]
    {"error":{"root_cause":[{"type":"status_exception","reason":"Model cannot be deleted in deploying or deployed state. Try undeploy model first then delete"}],"type":"status_exception","reason":"Model cannot be deleted in deploying or deployed state. Try undeploy model first then delete"},"status":400}
        at __randomizedtesting.SeedInfo.seed([4E5188680CFAD2E9:84740AFD7158DDDD]:0)
        at app//org.opensearch.client.RestClient.convertResponse(RestClient.java:501)
        at app//org.opensearch.client.RestClient.performRequest(RestClient.java:384)
        at app//org.opensearch.client.RestClient.performRequest(RestClient.java:359)
        at app//org.opensearch.ml.utils.TestHelper.makeRequest(TestHelper.java:182)
        at app//org.opensearch.ml.utils.TestHelper.makeRequest(TestHelper.java:155)
        at app//org.opensearch.ml.utils.TestHelper.makeRequest(TestHelper.java:144)
        at app//org.opensearch.ml.rest.MLCommonsRestTestCase.deleteModel(MLCommonsRestTestCase.java:654)
        at app//org.opensearch.ml.tools.ToolIntegrationWithLLMTest.deleteModel(ToolIntegrationWithLLMTest.java:75)
        at java.base@21.0.5/jdk.internal.reflect.DirectMethodHandleAccessor.invoke(DirectMethodHandleAccessor.java:103)

```
This is likely found here 
https://github.com/opensearch-project/ml-commons/blob/c84c9471917e28cc8c5571a5911bfd9a5fd0b904/plugin/src/test/java/org/opensearch/ml/tools/ToolIntegrationWithLLMTest.java#L63-L65

```
./gradlew ':opensearch-ml-plugin:integTest' --tests "org.opensearch.ml.rest.RestMLGuardrailsIT.testPredictRemoteModelFailedWithModelGuardrail" -Dtests.seed=4E5188680CFAD2E9 -Dtests.security.manager=false -Dtests.locale=mdf-RU -Dtests.timezone=America/Goose_Bay -Druntime.java=21

RestMLGuardrailsIT > testPredictRemoteModelFailedWithModelGuardrail FAILED
    java.lang.AssertionError: 
    Expected: (an instance of org.opensearch.client.ResponseException and exception with message a string containing "guardrails triggered for user input")
         but: exception with message a string containing "guardrails triggered for user input" message was "method [POST], host [http://[::1]:45733], URI [/_plugins/_ml/models/null/_deploy], status line [HTTP/1.1 404 Not Found]
    {"error":{"root_cause":[{"type":"status_exception","reason":"Failed to find model"}],"type":"status_exception","reason":"Failed to find model"},"status":404}"
    Stacktrace was: org.opensearch.client.ResponseException: method [POST], host [http://[::1]:45733], URI [/_plugins/_ml/models/null/_deploy], status line [HTTP/1.1 404 Not Found]
    {"error":{"root_cause":[{"type":"status_exception","reason":"Failed to find model"}],"type":"status_exception","reason":"Failed to find model"},"status":404}
    	at org.opensearch.client.RestClient.convertResponse(RestClient.java:501)
    	at org.opensearch.client.RestClient.performRequest(RestClient.java:384)
    	at org.opensearch.client.RestClient.performRequest(RestClient.java:359)
    	at org.opensearch.ml.utils.TestHelper.makeRequest(TestHelper.java:182)
    	at org.opensearch.ml.utils.TestHelper.makeRequest(TestHelper.java:155)
    	at org.opensearch.ml.utils.TestHelper.makeRequest(TestHelper.java:144)
    	at org.opensearch.ml.rest.RestMLGuardrailsIT.deployRemoteModel(RestMLGuardrailsIT.java:582)
    	at org.opensearch.ml.rest.RestMLGuardrailsIT.testPredictRemoteModelFailedWithModelGuardrail(RestMLGuardrailsIT.java:318)
    	at java.base/jdk.internal.reflect.DirectMethodHandleAccessor.invoke(DirectMethodHandleAccessor.java:103)
```
Which is found here
https://github.com/opensearch-project/ml-commons/blob/ab2fae3a2ed31f280055836621627587d39834ab/plugin/src/test/java/org/opensearch/ml/rest/RestMLGuardrailsIT.java#L581-L583

## Version
OS:2.18

I suspect there is some sort of race condition. I am noticing there is no retry involved nor is there a waitFor involved for creating this resource. 

This is also similar to https://github.com/opensearch-project/ml-commons/issues/3228

### PR DESCRIPTION
**Pull request by brianf-aws**
### Description
This PR attempts to remedy two Flaky classes 
- [RestMLGuardrailsIT.java](https://github.com/opensearch-project/ml-commons/compare/main...brianf-aws:ml-commons:flaky-it-involving-model-fix?expand=1#diff-b973f1adfdde1699a1f4f9a8b7d048b27c01c88c86a836c7c4cc3d6fbae970fb) Borrows code cleanup from https://github.com/opensearch-project/ml-commons/pull/3244 Which removes an extra call to the Task API to get the model id.
- [ToolIntegrationWithLLMTest.java](https://github.com/opensearch-project/ml-commons/compare/main...brianf-aws:ml-commons:flaky-it-involving-model-fix?expand=1#diff-072749d2af860644b27fbe28a9b486d52580d5845e9c82a537f28ed9dcd3cfd8) updates the class to specifically check for the status of the model by calling `GET /_plugins/_ml/models/ modelId` and actively blocking after 5 tries to make sure the model successfully undeployed before deleting which was the crux of the issue (`Model cannot be deleted in deploying or deployed state`). 

This PR also does some code improvement by more descriptive logging, variable naming, spacing. 

### Related Issues
Resolves #3237

### Check List
- [X] New functionality includes testing.
- [ ] New functionality has been documented.
- [ ] API changes companion pull request [created](https://github.com/opensearch-project/opensearch-api-specification/blob/main/DEVELOPER_GUIDE.md).
- [X] Commits are signed per the DCO using `--signoff`.
- [ ] Public documentation issue/PR [created](https://github.com/opensearch-project/documentation-website/issues/new/choose).

By submitting this pull request, I confirm that my contribution is made under the terms of the Apache 2.0 license.
For more information on following Developer Certificate of Origin and signing off your commits, please check [here](https://github.com/opensearch-project/ml-commons/blob/main/CONTRIBUTING.md#developer-certificate-of-origin).

### CODE REVIEW

File: plugin/src/test/java/org/opensearch/ml/tools/ToolIntegrationWithLLMTest.java [hunk 1]
```diff
@@ -72,16 +71,17 @@ public void stopMockLLM() {
     @After
     public void deleteModel() throws IOException {
         undeployModel(modelId);
+        checkForModelUndeployedStatus(modelId);
         deleteModel(client(), modelId, null);
     }
 
     @SneakyThrows
-    private void waitModelUndeployed(String modelId) {
```
Comment (dhrubo-os) [inline plugin/src/test/java/org/opensearch/ml/tools/ToolIntegrationWithLLMTest.java:79]: Seems like in [this PR](https://github.com/opensearch-project/ml-commons/pull/2510) we removed this line as this PR should fix this issue? Isn't that the case?

More back ground about this test here: https://github.com/opensearch-project/ml-commons/pull/2435#issuecomment-2164080756

File: plugin/src/test/java/org/opensearch/ml/rest/MLCommonsRestTestCase.java [hunk 2]
```diff
@@ -977,7 +977,7 @@ public void waitForTask(String taskId, MLTaskState targetState) throws Interrupt
             }
             return taskDone.get();
         }, CUSTOM_MODEL_TIMEOUT, TimeUnit.SECONDS);
-        assertTrue(taskDone.get());
+        assertTrue(String.format(Locale.ROOT, "Task Id %s could not get to %s state", taskId, targetState.name()), taskDone.get());
```
Comment (dhrubo-os) [inline plugin/src/test/java/org/opensearch/ml/rest/MLCommonsRestTestCase.java:980]: Cool!

File: plugin/src/test/java/org/opensearch/ml/tools/ToolIntegrationWithLLMTest.java (hunk 1 above)
Comment (brianf-aws) [reply plugin/src/test/java/org/opensearch/ml/tools/ToolIntegrationWithLLMTest.java:79]: Thanks for bringing that up, Im checking the communication thread and notice that Zane (@zane-neo) was trying to fix the issue after aforementioned PR that omitted the `waitModelUndeployed` method.

In summary I see the following happened (Based on this [PR thread](https://github.com/opensearch-project/ml-commons/issues/2419))
1. ([May 9th](https://github.com/opensearch-project/ml-commons/issues/2419#issuecomment-2103655878)) Looks like @b4sjoo Authored a PR that fixes this class issue by updating the transportUndeployAction class. By using a callback to notify when the undeployement occured. 
2. ([July 4th] (https://github.com/opensearch-project/ml-commons/pull/2613)) Zane references a issue following the same problem and the PR thread opens again. In their own words
> The reason is deploy model is in an async approach and when client received the response, the model status in index is not guaranteed to deployed, this doesn't have a simple fix since a lot of files are involved in deploy flow.
> This issue is not able to reproduced easily on local, .. and closing this PR now. [src](https://github.com/opensearch-project/ml-commons/pull/2613#issuecomment-2272518180)

What i believe this means is that because we are working with an Async operation we have to include this method to periodically check that the model has been undeployed before deleting it to get over the `    {"error":{"root_cause":[{"type":"status_exception","reason":"Model cannot be deleted in deploying or deployed state. Try undeploy model first then delete"}],"type":"status_exception","reason":"Model cannot be deleted in deploying or deployed state. Try undeploy model first then delete"},"status":400}
` issue.

**Review by dhrubo-os — APPROVED** [review]

**Review by mingshl — APPROVED** [review]
