### PR TITLE
fix error message with unwrapping the root cause

### LINKED ISSUE #2443: [BUG] agent execution error message
**What is the bug?**
Agent execution api will return the following error message if the root cause exception doesn't occur in coordinate node and is wrapped into remote transport exception.
```
"{\"error\":{\"reason\":\"Invalid Request\",\"details\":\"[d0aa9b912dfc3dacaf11334ad978ea34][x.x.x.x:x][cluster:admin/opensearch/ml/execute]\",\"type\":\"RemoteTransportException\"},\"status\":400}"
```

### PR DESCRIPTION
**Pull request by jngz-es**
### Description
Unwrap the root cause to return when agent execution gets an exception.
 
### Issues Resolved
resolve #2443
 
### Check List
- [ ] New functionality includes testing.
  - [ ] All tests pass
- [ ] New functionality has been documented.
  - [ ] New functionality has javadoc added
- [ ] Commits are signed per the DCO using --signoff 

By submitting this pull request, I confirm that my contribution is made under the terms of the Apache 2.0 license.
For more information on following Developer Certificate of Origin and signing off your commits, please check [here](https://github.com/opensearch-project/OpenSearch/blob/main/CONTRIBUTING.md#developer-certificate-of-origin).

### CODE REVIEW

File: plugin/src/main/java/org/opensearch/ml/utils/MLExceptionUtils.java [hunk 1]
```diff
@@ -59,4 +59,8 @@ public static void logException(String errorMessage, Exception e, Logger log) {
             log.error(errorMessage, e);
         }
     }
+
+    public static Throwable getRootCause(Throwable t) {
```
Comment (ylwu-amzn) [inline plugin/src/main/java/org/opensearch/ml/utils/MLExceptionUtils.java:63]: seems not necessary to create a new method for one line of code

File: plugin/src/main/java/org/opensearch/ml/utils/error/ErrorMessageFactory.java [hunk 2]
```diff
@@ -23,22 +24,9 @@ public static ErrorMessage createErrorMessage(Throwable e, int status) {
         int st = status;
         if (t instanceof OpenSearchException) {
             st = ((OpenSearchException) t).status().getStatus();
-        } else {
-            t = unwrapCause(e);
         }
+        t = MLExceptionUtils.getRootCause(t);
```
Comment (Hailong-am) [inline plugin/src/main/java/org/opensearch/ml/utils/error/ErrorMessageFactory.java:28]: would recommend to use `ExceptionsHelper.unwrapCause()` which provided by core library

https://github.com/opensearch-project/OpenSearch/blob/3fe66747b1523c74e06bc3465ef2ab682048f76b/libs/core/src/main/java/org/opensearch/ExceptionsHelper.java#L127-L145

Comment (zhichao-aws) [reply plugin/src/main/java/org/opensearch/ml/utils/error/ErrorMessageFactory.java:28]: +1

Comment (jngz-es) [reply plugin/src/main/java/org/opensearch/ml/utils/error/ErrorMessageFactory.java:28]: MLExceptionUtils.getRootCause(t) wraps the above function. What I was thinking is the existing class MLExceptionUtils is responsible for hosting all exception utilities in ml-commons, so I just simply wrap the above core function into this class to use for the entire ml-commons plugin.

File: plugin/src/main/java/org/opensearch/ml/utils/MLExceptionUtils.java (hunk 1 above)
Comment (jngz-es) [reply plugin/src/main/java/org/opensearch/ml/utils/MLExceptionUtils.java:63]: See my below comment please.

File: plugin/src/main/java/org/opensearch/ml/utils/error/ErrorMessageFactory.java (hunk 2 above)
Comment (jngz-es) [reply plugin/src/main/java/org/opensearch/ml/utils/error/ErrorMessageFactory.java:28]: Also it can provide flexibility for ml-commons plugin. If we needed to change the logic, we only needed to change the function MLExceptionUtils.getRootCause(t), not everywhere the core function used.

Comment (Hailong-am) [reply plugin/src/main/java/org/opensearch/ml/utils/error/ErrorMessageFactory.java:28]: > MLExceptionUtils.getRootCause(t) wraps the above function 

I think the logic between `ExceptionUtils.getRootCause(t)` and `ExceptionsHelper.unwrapCause()` is different. `getRootCause` is to get the root cause but `unwrapCause` used for unwrap `OpenSearchWrapperException` and not go deeper. They may produce different result.

Comment (jngz-es) [reply plugin/src/main/java/org/opensearch/ml/utils/error/ErrorMessageFactory.java:28]: Hi Hailong, I went through those two implementations and didn't see big differences. The only difference is about `ExceptionsHelper.unwrapCause()` having 10 times limitation on the extracting loop.

**Review by ylwu-amzn — APPROVED** [review]

File: plugin/src/main/java/org/opensearch/ml/utils/error/ErrorMessageFactory.java (hunk 2 above)
Comment (Hailong-am) [reply plugin/src/main/java/org/opensearch/ml/utils/error/ErrorMessageFactory.java:28]: > The only difference is about ExceptionsHelper.unwrapCause() having 10 times limitation on the extracting loop.

I guess the difference is that ExceptionsHelper.unwrapCause() will stop if the cause is not instance of `OpenSearchWrapperException`. I don't know if there has a case the cause is not `OpenSearchWrapperException` and still have inner cause.

Comment (jngz-es) [reply plugin/src/main/java/org/opensearch/ml/utils/error/ErrorMessageFactory.java:28]: `OpenSearchWrapperException` is reusing the standard `throwable` `getCause` interface to unwrap. I prefer to use the method from the library `org.apache.commons.lang3.exception` which covers the method `ExceptionsHelper.unwrapCause()`.

**Review by Zhangxunmt — APPROVED** [review]

**Comment by yuye-aws** [comment]
@jngz-es Shall we also backport this PR to 2.14 and 2.15 branch? The multi node IT is currently excluded for search index tool.
