### PR TITLE
fix: wrong error code when deleting memory container

### LINKED ISSUE #4706: Delete Memory Container API returns 500 instead of 404 for non-existent container
When attempting to delete a memory container that doesn't exist, the API returns `500 INTERNAL_SERVER_ERROR` instead of the more appropriate `404 NOT_FOUND` status code.

Relevant code:

TransportDeleteMemoryContainerAction.java https://github.com/opensearch-project/ml-commons/blob/main/plugin/src/main/java/org/opensearch/ml/action/memorycontainer/TransportDeleteMemoryContainerAction.java#L159-L162

### PR DESCRIPTION
**Pull request by b4sjoo**
#### Summary
This PR fixes incorrect HTTP status codes returned when deleting memory containers and refactors index deletion logic.
#### Changes
1. Error handling
* Preserve 4XX client errors: When `getMemoryContainer` or `deleteIndex` fails with an `OpenSearchStatusException` in the 4xx range, the original status and message are returned instead of a generic 500.
* `ResourceNotFoundException` → 404: Index deletion failures due to `ResourceNotFoundException` are now mapped to `RestStatus.NOT_FOUND` instead of `INTERNAL_SERVER_ERROR`.
2. `MemoryConfiguration` (getIndexName)
* `LONG_TERM`: Returns `null` when `llmId` is null or `strategies` is null/empty, so long-term memory is only used when properly configured.
* `HISTORY`: Returns `null` when `getLongMemoryIndexName()` is null, so history is disabled when long-term memory is not configured.
3. `TransportDeleteMemoryContainerAction` refactor
* Unified index deletion: `deleteAllMemoryIndices` is merged into `deleteSelectiveMemoryIndices`. “Delete all” is implemented by passing `EnumSet.allOf(MemoryType.class)`.
* Logging: Uses `ALL_INDICES_DELETED` vs `SELECTIVE_INDICES_DELETED` based on whether all indices were deleted.
* Partial index deletion: Adds a warning when some requested memory types have no index (e.g., disabled or not configured).
#### Testing
* Updated tests to provide `llmId` and `strategies` where `LONG_TERM` or `HISTORY` index names are required.
* All relevant tests pass.

### Related Issues
Resolves #4706 

### Check List
- [ ] New functionality includes testing.
- [ ] New functionality has been documented.
- [ ] API changes companion pull request [created](https://github.com/opensearch-project/opensearch-api-specification/blob/main/DEVELOPER_GUIDE.md).
- [ ] Commits are signed per the DCO using `--signoff`.
- [ ] Public documentation issue/PR [created](https://github.com/opensearch-project/documentation-website/issues/new/choose).

By submitting this pull request, I confirm that my contribution is made under the terms of the Apache 2.0 license.
For more information on following Developer Certificate of Origin and signing off your commits, please check [here](https://github.com/opensearch-project/ml-commons/blob/main/CONTRIBUTING.md#developer-certificate-of-origin).

### CODE REVIEW

**Comment by b4sjoo** [comment]
> When deleteAllMemories is true but deleteMemories is also non-null, the code uses
> EnumSet.allOf(MemoryType.class) which is correct. However, when deleteAllMemories is
> false and deleteMemories is null, typesToDelete will be null, which will cause a
> NullPointerException in deleteSelectiveMemoryIndices when iterating over
> deleteMemories. A null check should be added before calling the method.

Tested in such case `DELETE /_plugins/_ml/memory_containers/{{container_id}}?delete_all_memories=false`, it is able to correctly delete the container

**Comment by b4sjoo** [comment]
> The warning condition indicesToDelete.size() != deleteMemories.size() is incorrect
> because indicesToDelete contains index name strings while deleteMemories contains
> MemoryType enum values. Some memory types may legitimately return null index names
> (e.g., disabled or unconfigured types), so this comparison will produce
> false-positive warnings. The check should instead track how many requested types had
> valid (non-null) index names and compare against the total requested types count.

Rationale here is we want to log down if there's a inconsistency between user's request and the indices the service delete, so this is expected.

**Comment by dhrubo-os** [comment]
```

Tests with failures:
 - org.opensearch.ml.action.memorycontainer.memory.TransportHybridSearchMemoriesActionTests.testDoExecute_NonEmptyPostFilter_Applied
 - org.opensearch.ml.action.memorycontainer.memory.TransportHybridSearchMemoriesActionTests.testDoExecute_SystemIndex_SearchFailure_WrapsException
 - org.opensearch.ml.action.memorycontainer.memory.TransportHybridSearchMemoriesActionTests.testDoExecute_AdminUser_NoOwnerFilter
 - org.opensearch.ml.action.memorycontainer.memory.TransportHybridSearchMemoriesActionTests.testDoExecute_WithMinScoreAndFilter
 - org.opensearch.ml.action.memorycontainer.memory.TransportHybridSearchMemoriesActionTests.testDoExecute_Success
 - org.opensearch.ml.action.memorycontainer.memory.TransportHybridSearchMemoriesActionTests.testDoExecute_NonAdminUser_OwnerFilterApplied
 - org.opensearch.ml.action.memorycontainer.memory.TransportHybridSearchMemoriesActionTests.testDoExecute_Success_WithSystemIndex


```

File: common/src/main/java/org/opensearch/ml/common/memorycontainer/MemoryConfiguration.java [hunk 1]
```diff
@@ -357,10 +357,15 @@ public String getIndexName(MemoryType memoryType) {
             return null;
         }
         // Check if disabled
```
Comment (akolarkunnu) [inline common/src/main/java/org/opensearch/ml/common/memorycontainer/MemoryConfiguration.java]: nit: Please update this comment based on new validation

File: common/src/main/java/org/opensearch/ml/common/memorycontainer/MemoryConfiguration.java [hunk 2]
```diff
@@ -357,10 +357,15 @@ public String getIndexName(MemoryType memoryType) {
...
+        if (memoryType == MemoryType.LONG_TERM
+            && (this.getLlmId() == null || this.getStrategies() == null || this.getStrategies().isEmpty())) {
```
Comment (ylwu-amzn) [inline common/src/main/java/org/opensearch/ml/common/memorycontainer/MemoryConfiguration.java]: **Behavior change with broad impact**: `getIndexName(LONG_TERM)` previously **never returned null**. With this change, it returns null when `llmId` or `strategies` are missing. Multiple callers outside this PR pass `getLongMemoryIndexName()` directly to search/index requests without null checks:

- `MemoryOperationsService.java:77` — used in IndexRequest/UpdateRequest/DeleteRequest
- `TransportSemanticSearchMemoriesAction.java:110` — `.indices(getLongMemoryIndexName())`
- `TransportHybridSearchMemoriesAction.java:125` — `new SearchRequest(getLongMemoryIndexName())`
- `MemorySearchService.java:87` — used in SearchDataObjectRequest
- `TransportAddMemoriesAction.java:413` — passed to `createFactMemoriesFromList`

If any of these paths are reached with a misconfigured container (no llmId/strategies), they'll throw NPE instead of a meaningful error. The logic is correct, but the callers need to be audited — either add null guards at each call site, or fail early when the container is fetched.

File: common/src/main/java/org/opensearch/ml/common/memorycontainer/MemoryConfiguration.java [hunk 3]
```diff
@@ -357,10 +357,15 @@ public String getIndexName(MemoryType memoryType) {
...
+            return null;
+        }
         if (memoryType == MemoryType.SESSIONS && isDisableSession()) {
             return null;
         }
```
Comment (ylwu-amzn) [inline common/src/main/java/org/opensearch/ml/common/memorycontainer/MemoryConfiguration.java:371]: The condition `getLlmId() == null || getStrategies() == null || getStrategies().isEmpty()` is duplicated for both LONG_TERM (line 360-362) and HISTORY (line 368). Consider extracting:

```java
private boolean isLongTermMemoryDisabled() {
    return getLlmId() == null || getStrategies() == null || getStrategies().isEmpty();
}
```

Then use it in both checks. This also makes the intent clearer — HISTORY depends on long-term memory being configured.

File: plugin/src/test/java/org/opensearch/ml/helper/MemoryContainerHelperTests.java [hunk 4]
```diff
@@ -221,24 +224,35 @@ public void testCheckMemoryAccess() {
...
+            .llmId("test-llm")
+            .strategies(strategies)
             .build();
 
         MLMemoryContainer container = createContainerBuilder().configuration(configuration).build();
         assertNotNull(helper.getMemoryIndexName(container, MemoryType.LONG_TERM));
         assertNull(helper.getMemoryIndexName(container, null));
 
-        // Test with null configuration - returns default index name
+        // Test with null configuration - returns null (no index name when config is missing)
```
Comment (ylwu-amzn) [inline plugin/src/test/java/org/opensearch/ml/helper/MemoryContainerHelperTests.java:253]: This is a behavior change in the test expectation: previously `getMemoryIndexName(containerNullConfig, MemoryType.LONG_TERM)` returned `.plugins-ml-am-default-memory-long-term` (non-null), now it returns null.

This means any code path that creates a container with default/null configuration and then tries to access the long-term index will now get null. Worth verifying there's no production path that relies on the old default-index-name behavior.

File: plugin/src/main/java/org/opensearch/ml/action/memorycontainer/TransportDeleteMemoryContainerAction.java [hunk 5]
```diff
@@ -334,19 +282,23 @@ private void deleteSelectiveMemoryIndices(
...
-                    memoryContainerId,
-                    indicesToDelete,
-                    deleteMemories
-                );
-
+            boolean isDeleteAll = deleteMemories.containsAll(EnumSet.allOf(MemoryType.class));
+            if (indicesToDelete.size() != deleteMemories.size()) {
+                log
+                    .warn(
+                        "Some memory indices were not found for container: {}, requested types: {}, found indices: {}",
```
Comment (rithinpullela) [inline plugin/src/main/java/org/opensearch/ml/action/memorycontainer/TransportDeleteMemoryContainerAction.java]: Nit: This warning will fire on every delete-all request for containers without long-term memory configured, since getIndexName(LONG_TERM) and getIndexName(HISTORY) now return null. That's normal operation, not something worth warning about.

File: common/src/main/java/org/opensearch/ml/common/memorycontainer/MemoryConfiguration.java (hunk 1 above)
Comment (b4sjoo) [reply common/src/main/java/org/opensearch/ml/common/memorycontainer/MemoryConfiguration.java]: Deleted

File: plugin/src/main/java/org/opensearch/ml/action/memorycontainer/TransportDeleteMemoryContainerAction.java (hunk 5 above)
Comment (b4sjoo) [reply plugin/src/main/java/org/opensearch/ml/action/memorycontainer/TransportDeleteMemoryContainerAction.java]: Removed

File: common/src/main/java/org/opensearch/ml/common/memorycontainer/MemoryConfiguration.java (hunk 2 above)
Comment (b4sjoo) [reply common/src/main/java/org/opensearch/ml/common/memorycontainer/MemoryConfiguration.java]: Checked and tested, works fine.
