### PR TITLE
[FIX] Simplify USER_PREFERENCE prompt to produce plain sentences

### LINKED ISSUE #4780: silently discards strategy results when LLM returns malformed JSON
### Description

When `infer: true` is used with Agentic Memory and the configured LLM returns malformed JSON for a strategy's fact extraction, the result is silently discarded. No error is returned in the API response, no warning is logged, and the caller has no way to know that a strategy failed. The API returns 200 and other strategies (e.g., SEMANTIC, SUMMARY) succeed normally.

This was observed with the `USER_PREFERENCE` strategy, whose internal prompt requires a complex output format (`"Preference sentence. Context: <why/how>. Categories: cat1,cat2"`). Claude Haiku 3 v2 produces invalid JSON for this format, while Haiku 4.5 and Sonnet 4.6 handle it correctly. However, the core issue is not model-specific — any LLM that produces malformed JSON will trigger the same silent failure.

### Steps to Reproduce

1. Create a memory container with USER_PREFERENCE strategy and a smaller LLM (e.g., Claude Haiku 3 v2):

```json
POST /_plugins/_ml/memory_containers/_create
{
  "name": "test",
  "configuration": {
    "embedding_model_id": "<embedding-model>",
    "embedding_model_type": "TEXT_EMBEDDING",
    "embedding_dimension": 384,
    "llm_id": "<claude-haiku-3-v2-model>",
    "disable_session": true,
    "strategies": [
      { "type": "SEMANTIC", "namespace": ["customer_id"] },
      { "type": "USER_PREFERENCE", "namespace": ["customer_id"] },
      { "type": "SUMMARY", "namespace": ["customer_id"] }
    ]
  }
}
```

2. Add a memory with `infer: true` containing clear user preferences.

3. API returns 200. SEMANTIC and SUMMARY produce long-term memories. USER_PREFERENCE produces 0 memories with no error.

### Expected Behavior

When a strategy's LLM output fails to parse, the system should:
- Log a WARNING with the strategy type and the raw LLM output
- Ideally, include a `warnings` array in the API response indicating which strategies failed

### Actual Behavior

- API returns 200 with `working_memory_id` — appears fully successful
- SEMANTIC: ✅ memories created
- SUMMARY: ✅ memories created
- USER_PREFERENCE: ❌ 0 memories, no error, no warning

The only way to discover the failure is to search long-term memory and notice the missing strategy type, or to read DEBUG-level OpenSearch logs and find the malformed JSON in the LLM response.

### Root Cause (from DEBUG logs)

The LLM returns malformed JSON where the array bracket is misplaced:

```json
{"facts":["I prefer phone calls...Categories: communication,time_preference"],
"I am not a morning person...Categories: time_preference",
"Wife Sarah...Categories: relationships,decision_making"]}
```

The `Context:` / `Categories:` format within each fact string contains commas that confuse smaller models into breaking the JSON array structure.

### Test Results by Model

| Model | SEMANTIC | SUMMARY | USER_PREFERENCE |
|-------|----------|---------|-----------------|
| Claude Haiku 3 v2 | ✅ | ✅ | ❌ silent failure |
| Claude Haiku 4.5 | ✅ | ✅ | ✅ |
| Claude Sonnet 4.6 | ✅ | ✅ | ✅ |

### Suggested Fixes

1. **Log a WARNING on JSON parse failure** — Include strategy type and raw LLM output. This is the minimum fix.
2. **Return parse failures in the API response** — Add a `warnings` field so callers can detect partial failures.
3. **Consider simplifying the USER_PREFERENCE prompt** — The `Context:` / `Categories:` format is more complex than SEMANTIC's plain facts format, making it more prone to JSON errors with smaller models.

### Environment

- OpenSearch: 3.6.0 (Docker, `opensearchstaging/opensearch:3.6.0`)
- Failing LLM: Claude Haiku 3 v2 via Bedrock Converse API
- Working LLMs: Claude Haiku 4.5, Claude Sonnet 4.6 via Bedrock Converse API
- Embedding: Local pretrained all-MiniLM-L12-v2

### PR DESCRIPTION
**Pull request by dhrubo-os**
### Description

Simplify the USER_PREFERENCE extraction prompt to produce plain self-contained sentences instead of the structured `Context:/Categories:` format. Also improve error logging when JSON parsing fails to include the strategy type.

**Before:**
```
"Bob prefers phone calls over email. Context: wife Sarah is hard of hearing. Categories: communication,time_preference"
```

**After:**
```
"Bob always prefers phone calls over email because his wife Sarah is hard of hearing."
```

### Motivation

1. **Fixes silent JSON parse failures with smaller LLMs** — The `Context: <why/how>. Categories: cat1,cat2` format contains commas inside JSON string values that confuse smaller models (e.g., Claude Haiku 3) into producing malformed JSON. When this happens, USER_PREFERENCE results are silently discarded with no error returned to the caller. Plain sentences eliminate this failure mode.

2. **Improves search quality** — The `Context:` and `Categories:` boilerplate text was stored in the `memory` field alongside the actual preference, diluting embedding quality for semantic search and creating false keyword matches for BM25/hybrid search. Plain sentences produce cleaner embeddings.

3. **No downstream consumers** — The Context and Categories metadata is not consumed by any code path today — no filtering by category, no surfacing of context to users.

### Testing

Validated on LoCoMo benchmark (1,540 questions, 10 conversations) with Claude Sonnet 4.6. USER_PREFERENCE extraction count actually increased slightly (685 vs 678 baseline).

### Issues Resolved

Resolves #4780

### Check List
- [x] New functionality includes testing
- [x] Commits are signed per the DCO using `--signoff`

### CODE REVIEW

File: common/src/main/java/org/opensearch/ml/common/memorycontainer/MemoryContainerConstants.java [hunk 1]
```diff
@@ -216,12 +215,14 @@ public class MemoryContainerConstants {
             </EXTRACT>
 
             <STYLE & RULES>
-            • One sentence per preference; merge related details; no duplicates; preserve user wording and numbers; avoid relative time; keep each fact < 350 chars.
-            • Format: "Preference sentence. Context: <why/how>. Categories: cat1,cat2"
+            • One self-contained sentence per preference. Include the subject's name and enough context to be meaningful on its own.
+            • Merge closely related details into the same sentence. No duplicates.
+            • Preserve user wording, names, numbers, and units. Include relative time references when no absolute date is available.
```
Comment (ylwu-amzn) [inline common/src/main/java/org/opensearch/ml/common/memorycontainer/MemoryContainerConstants.java]: Use relative time may cause confusion later. For example, if user say "2 weeks ago", after 1 week, the relative time becomes wrong.

File: common/src/main/java/org/opensearch/ml/common/memorycontainer/MemoryContainerConstants.java [hunk 2]
```diff
@@ -197,9 +197,8 @@ public class MemoryContainerConstants {
             Respond NOW with ONE LINE of valid JSON ONLY exactly as {"facts":["fact1","fact2",...]}. No extra text, no code fences, no newlines or tabs, no spaces after commas or colons.""";
 
     // JSON enforcement message for user preference extraction
-    public static final String USER_PREFERENCE_JSON_ENFORCEMENT_MESSAGE =
-        """
-            Return ONLY ONE LINE of valid JSON exactly as {"facts":["<Preference sentence>. Context: <why/how>. Categories: <cat1,cat2>"]}. Begin with { and end with }. No extra text.""";
+    public static final String USER_PREFERENCE_JSON_ENFORCEMENT_MESSAGE = """
+        Return ONLY ONE LINE of valid JSON exactly as {"facts":["<fact sentence>"]}. Begin with { and end with }. No extra text.""";
```
Comment (ylwu-amzn) [inline common/src/main/java/org/opensearch/ml/common/memorycontainer/MemoryContainerConstants.java:201]: Nit: the sibling constant `JSON_ENFORCEMENT_MESSAGE` directly above uses
```java
public static final String JSON_ENFORCEMENT_MESSAGE =
    """
        Respond NOW with ...""";
```
but this one puts `"""` on the same line as `=` with shallower content indentation. Matching the surrounding style would be a small readability win and also keeps the Java text-block incidental-whitespace stripping rules identical between the two constants.

File: common/src/main/java/org/opensearch/ml/common/memorycontainer/MemoryContainerConstants.java [hunk 3]
```diff
@@ -197,9 +197,8 @@ public class MemoryContainerConstants {
             Respond NOW with ONE LINE of valid JSON ONLY exactly as {"facts":["fact1","fact2",...]}. No extra text, no code fences, no newlines or tabs, no spaces after commas or colons.""";
 
     // JSON enforcement message for user preference extraction
-    public static final String USER_PREFERENCE_JSON_ENFORCEMENT_MESSAGE =
-        """
-            Return ONLY ONE LINE of valid JSON exactly as {"facts":["<Preference sentence>. Context: <why/how>. Categories: <cat1,cat2>"]}. Begin with { and end with }. No extra text.""";
```
Comment (ylwu-amzn) [inline common/src/main/java/org/opensearch/ml/common/memorycontainer/MemoryContainerConstants.java:202]: Why remove Context/Categories ? Will this break current code ?

File: common/src/main/java/org/opensearch/ml/common/memorycontainer/MemoryContainerConstants.java (hunk 2 above)
Comment (dhrubo-os) [inline common/src/main/java/org/opensearch/ml/common/memorycontainer/MemoryContainerConstants.java:201]: Fixed — now matches the sibling `JSON_ENFORCEMENT_MESSAGE` style.

File: common/src/main/java/org/opensearch/ml/common/memorycontainer/MemoryContainerConstants.java (hunk 3 above)
Comment (dhrubo-os) [inline common/src/main/java/org/opensearch/ml/common/memorycontainer/MemoryContainerConstants.java:202]: No code path consumes Context or Categories today — there's no filtering by category and no surfacing of context metadata to users or agents. The entire string (including the metadata) gets stored in the `memory` field and embedded as-is, which actually hurts search quality by diluting the embedding with boilerplate text.

The main motivation is #4780 — the `Context: <why/how>. Categories: cat1,cat2` format causes smaller LLMs (e.g., Claude Haiku) to produce malformed JSON because the commas inside `Categories: cat1,cat2` confuse the model into breaking the JSON array structure. With plain sentences, Haiku 4.5 successfully extracts all USER_PREFERENCE memories (verified in testing).

This won't break existing code — the `memory` field is a free-text string, and downstream code only reads it as-is. No parser expects the `Context:/Categories:` structure.

**Review by dhrubo-os — COMMENTED** [review]
Thanks for the review Yaliang!

**Comment by dhrubo-os** [comment]
Correction on the relative time comment: You're right @ylwu-amzn — this was indeed a change introduced in this PR, not from #4658. I've fixed it — the prompt now says "Avoid relative time references; use absolute dates when available", consistent with the original behavior. Thanks for catching this!

**Review by rithinpullela — APPROVED** [review]
LGTM!

One small suggestion for the future: Instead of making the LLMs return in a JSON format asking them to make a tool call results in less errors. The models are trained on tool calls and hence they are really good at using tools rather than responding in a particular format. I saw the same behavior with models like Opus 4.5

**Comment by dhrubo-os** [comment]
> LGTM!
> 
> One small suggestion for the future: Instead of making the LLMs return in a JSON format asking them to make a tool call results in less errors. The models are trained on tool calls and hence they are really good at using tools rather than responding in a particular format. I saw the same behavior with models like Opus 4.5

Good Idea, created an issue as an placeholder for this: https://github.com/opensearch-project/ml-commons/issues/4799

**Review by ylwu-amzn — APPROVED** [review]
