### PR TITLE
add fixed in time rcf

### LINKED ISSUE #139: Integrate RCF to support anomaly detection on time-series data
We have released AD plugin two years ago based on RCF. Similarly we can integrate RCF to MLCommons to support anomaly detection, just like AD historical analysis.

### PR DESCRIPTION
**Pull request by ylwu-amzn**
Signed-off-by: Yaliang Wu <ylwu@amazon.com>

### Description
Integrate RCF to support anomaly detection on time-series data.

Related PR: https://github.com/aws/random-cut-forest-by-aws/pull/298
 
### Issues Resolved
#139
 
### Check List
- [x] New functionality includes testing.
  - [x] All tests pass
- [x] New functionality has been documented.
  - [x] New functionality has javadoc added
- [x] Commits are signed per the DCO using --signoff 

By submitting this pull request, I confirm that my contribution is made under the terms of the Apache 2.0 license.
For more information on following Developer Certificate of Origin and signing off your commits, please check [here](https://github.com/opensearch-project/OpenSearch/blob/main/CONTRIBUTING.md#developer-certificate-of-origin).

### CODE REVIEW

File: ml-algorithms/src/main/java/org/opensearch/ml/engine/algorithms/rcf/FixedInTimeRandomCutForest.java [hunk 1]
```diff
@@ -0,0 +1,191 @@
...
+                    }
+                } else {
+                    pointList.add(value.doubleValue());
+                }
+            }
+            double[] point = pointList.stream().mapToDouble(d -> d).toArray();
+            pointList.clear();
+            Map<String, Object> result = new HashMap<>();
+
+            AnomalyDescriptor process = forest.process(point, timestamp);
```
Comment (kaituo) [inline ml-algorithms/src/main/java/org/opensearch/ml/engine/algorithms/rcf/FixedInTimeRandomCutForest.java:161]: process includes both score and update.  How do you prevent training from happening?

**Review by kaituo — APPROVED** [review]

File: ml-algorithms/src/main/java/org/opensearch/ml/engine/algorithms/rcf/FixedInTimeRandomCutForest.java (hunk 1 above)
Comment (ylwu-amzn) [reply ml-algorithms/src/main/java/org/opensearch/ml/engine/algorithms/rcf/FixedInTimeRandomCutForest.java:161]: Thanks Kaituo, I have the same question and waiting for ML team's response. I created an issue to make this discussion open on RCF repo https://github.com/aws/random-cut-forest-by-aws/issues/299

**Review by jackiehanyang — APPROVED** [review]
