### PR TITLE
fix ML task index mapping

### LINKED ISSUE #2948: [BUG] ML task index mapping is wrong
ML task index mapping is wrong, `remote_job` field part will be ignored. 
https://github.com/opensearch-project/ml-commons/blob/main/common/src/main/java/org/opensearch/ml/common/CommonValue.java#L353
```
{
    "_meta": {"schema_version": 3},
    "properties": {
      "model_id": {"type": "keyword"},
      "task_type": {"type": "keyword"},
      "function_name": {"type": "keyword"},
      "state": {"type": "keyword"},
      "input_type": {"type": "keyword"},
      "progress": {"type": "float"},
      "output_index": {"type": "keyword"},
      "worker_node": {"type": "keyword"},
      "create_time": {"type": "date", "format": "strict_date_time||epoch_millis"},
      "last_update_time": {"type": "date", "format": "strict_date_time||epoch_millis"},
      "error": {"type": "text"},
      "is_async" : {"type" : "boolean"}, 
      "user": {
        "type": "nested",
        "properties": {
          "name": {"type":"text", "fields":{"keyword":{"type":"keyword", "ignore_above":256}}},
          "backend_roles": {"type":"text", "fields":{"keyword":{"type":"keyword"}}},
          "roles": {"type":"text", "fields":{"keyword":{"type":"keyword"}}},
          "custom_attribute_names": {"type":"text", "fields":{"keyword":{"type":"keyword"}}}
        }
      }
    }
},"remote_job" : {"type": "flat_object"}
    }
}
```

### PR DESCRIPTION
**Pull request by ylwu-amzn**
### Description
Fix ML task index mapping

### Related Issues
Resolves #2948

### Check List
- [ ] New functionality includes testing.
- [ ] New functionality has been documented.
- [ ] API changes companion pull request [created](https://github.com/opensearch-project/opensearch-api-specification/blob/main/DEVELOPER_GUIDE.md).
- [ ] Commits are signed per the DCO using `--signoff`.
- [ ] Public documentation issue/PR [created](https://github.com/opensearch-project/documentation-website/issues/new/choose).

By submitting this pull request, I confirm that my contribution is made under the terms of the Apache 2.0 license.
For more information on following Developer Certificate of Origin and signing off your commits, please check [here](https://github.com/opensearch-project/ml-commons/blob/main/CONTRIBUTING.md#developer-certificate-of-origin).

### CODE REVIEW

File: common/src/main/java/org/opensearch/ml/common/CommonValue.java [hunk 1]
```diff
@@ -391,11 +391,10 @@ public class CommonValue {
         + "      \""
         + MLTask.IS_ASYNC_TASK_FIELD
         + "\" : {\"type\" : \"boolean\"}, \n"
-        + USER_FIELD_MAPPING
-        + "    }\n"
-        + "}"
+        + "      \""
         + MLTask.REMOTE_JOB_FIELD
-        + "\" : {\"type\": \"flat_object\"}\n"
+        + "\" : {\"type\": \"flat_object\"}, \n"
```
Comment (dhrubo-os) [inline common/src/main/java/org/opensearch/ml/common/CommonValue.java:396]: if we want to keep the consistency with other fields may be we can add  `+ "      \""` after this?

Comment (ylwu-amzn) [reply common/src/main/java/org/opensearch/ml/common/CommonValue.java:396]: Not quite get you, that will bring extra `\"` which will be a wrong index mapping

Comment (dhrubo-os) [reply common/src/main/java/org/opensearch/ml/common/CommonValue.java:396]: Sorry the confusion. Please ignore my comment.

**Review by dhrubo-os — APPROVED** [review]

**Review by Zhangxunmt — APPROVED** [review]
