### PR TITLE
[BUG FIX] Add expiry time to master key cache to prevent stale encryption key usage

### LINKED ISSUE #4542: [BUG] Add expiry time to master key cache to prevent stale encryption key usage
In multi-tenant environment, We store master keys for tenants in an in-memory HashMap ([code ref](https://github.com/opensearch-project/ml-commons/blob/main/ml-algorithms/src/main/java/org/opensearch/ml/engine/
encryptor/EncryptorImpl.java#L65)). Currently, entries never expire, which can cause decryption failures in the following edge case:

Steps to Reproduce:

1. T1: Create a model → encryption key is cached in the map
2. T2: Delete the collection/domain
3. T3: Create a new collection/domain with the same name
4. T4: Create a model → uses stale encryption key from T1 (still in cache) to encrypt credentials
5. T5: Deployment occurs → HashMap is reset
6. T6: Predict on the model created at T4 → fails because:
   - Key not in cache (reset at T5)
   - Key not in index (new domain from T3)
   - New key is generated, but credentials were encrypted with the old key from T1

Root Cause:

The cache doesn't expire entries, so stale encryption keys persist across collection/domain recreation cycles.

Proposed Solution:

Add a TTL (e.g., 5 minutes) to cache entries. When an entry expires, fetch the encryption key from the index/DDB instead of using the cached value. This ensures we always use the correct encryption key for the current domain.

### PR DESCRIPTION
**Pull request by arjunkumargiri**
### Description

Fixes #4542 

This PR adds TTL-based expiry to the master key cache in `EncryptorImpl` to prevent stale encryption key usage in multi-tenant environments.

#### 1. Cache with TTL
- Replaced `ConcurrentHashMap<String, String>` with Guava's `Cache<String, String>`
- Added 5-minute TTL using `CacheBuilder.expireAfterWrite(5, TimeUnit.MINUTES)`
- When entries expire, keys are automatically re-fetched from the index/DDB
- This ensures we always use the correct encryption key for the current domain

#### 2. Race Condition Fix
Fixed a potential race condition where the key could expire between the cache check and usage:
- Introduced `getOrInitMasterKey()` method that atomically retrieves and returns the key
- Updated `encrypt()` and `decrypt()` to store the key in a local variable
- Prevents `NullPointerException` if cache expires mid-operation

#### 3. Testability
- Added package-private constructors accepting custom TTL for testing
- Allows tests to use 1-second TTL instead of waiting 5 minutes

### Changes

**EncryptorImpl.java:**
- Replaced `Map<String, String>` with `Cache<String, String>` with 5-minute expiry
- Added `MASTER_KEY_CACHE_TTL_MINUTES` constant (5 minutes)
- Added package-private constructors with configurable TTL for testing
- Introduced `getOrInitMasterKey()` to prevent race conditions
- Updated `createJceMasterKey()` to accept the key directly instead of tenant ID
- Updated all cache access to use `getIfPresent()` instead of `get()`

**EncryptorImplTest.java:**
- Added 5 comprehensive tests covering cache behavior:
  - `testMasterKeyRefetchAfterCacheExpiry()` - Verifies cache reuse and no redundant DDB calls
  - `testCacheExpiryConfiguration()` - Verifies DDB is called only once when key is cached
  - `testStaleMasterKeyScenarioWithCacheExpiry()` - Tests actual cache expiry with 1-second TTL
  - `testMultipleTenantsCacheIndependently()` - Ensures tenant isolation
  - `testCacheReturnsNullForExpiredKey()` - Validates null returns for missing keys
- Added `verify()` assertions to confirm DDB call counts
- Removed redundant tests

### Testing

All existing tests pass, plus 5 new tests specifically for cache expiry:

```bash
./gradlew :opensearch-ml-algorithms:test --tests "EncryptorImplTest"

### CODE REVIEW

**Comment by ylwu-amzn** [comment]
Spotless check failed. Run './gradlew spotlessApply' to fix.

File: ml-algorithms/src/main/java/org/opensearch/ml/engine/encryptor/EncryptorImpl.java [hunk 1]
```diff
@@ -62,23 +65,41 @@ public class EncryptorImpl implements Encryptor {
...
-    private final Map<String, String> tenantMasterKeys;
+    private final Cache<String, String> tenantMasterKeys;
     private MLIndicesHandler mlIndicesHandler;
 
     // concurrent map can't have null as a key. This is to support single tenancy
     // assigning some random string so that it can't be duplicate
     public static final String DEFAULT_TENANT_ID = "03000200-0400-0500-0006-000700080009";
+    
+    // TTL for master key cache entries (5 minutes)
+    private static final long MASTER_KEY_CACHE_TTL_MINUTES = 5;
```
Comment (ylwu-amzn) [inline ml-algorithms/src/main/java/org/opensearch/ml/engine/encryptor/EncryptorImpl.java]: Should we make this configurable ?
The key will be removed from cache every 5 minutes. Then will retrieve it from index and put into cache. That may add some latency overhead.

Comment (brianf-aws) [reply ml-algorithms/src/main/java/org/opensearch/ml/engine/encryptor/EncryptorImpl.java]: Agree with @ylwu-amzn  domain upgrade or restart of OS will be a bit unlikely so eventually it should refresh from datastore.

Also having it configurable has an operator an option to step in and refresh users key if they happen to report a problem.

File: ml-algorithms/src/main/java/org/opensearch/ml/engine/encryptor/EncryptorImpl.java [hunk 2]
```diff
@@ -62,23 +65,41 @@ public class EncryptorImpl implements Encryptor {
...
 
     public EncryptorImpl(String tenantId, String masterKey) {
-        this.tenantMasterKeys = new ConcurrentHashMap<>();
+        this(tenantId, masterKey, MASTER_KEY_CACHE_TTL_MINUTES, TimeUnit.MINUTES);
+    }
+
+    // Package-private constructor for testing with custom TTL
+    EncryptorImpl(String tenantId, String masterKey, long cacheTtl, TimeUnit timeUnit) {
+        this.tenantMasterKeys = CacheBuilder.newBuilder()
+            .expireAfterWrite(cacheTtl, timeUnit)
```
Comment (brianf-aws) [inline ml-algorithms/src/main/java/org/opensearch/ml/engine/encryptor/EncryptorImpl.java:132]: If we make TTL very long, can we add logging so operators have visibility on evictions? While I do think your PR will solve tag mismatch issues  but we wouldn't be able to get a hint about the key in memory/cache

```
EncryptorImpl(String tenantId, String masterKey, long cacheTtl, TimeUnit timeUnit) {
    this.tenantMasterKeys = CacheBuilder.newBuilder()
        .expireAfterWrite(cacheTtl, timeUnit)
        .removalListener((RemovalNotification<String, MasterKey> notification) -> 
            logger.info("Cache entry removed - Key: {}, Cause: {}", 
                notification.getKey(), 
                notification.getCause()))
        .build();
}
```

File: ml-algorithms/src/test/java/org/opensearch/ml/engine/encryptor/EncryptorImplTest.java
Comment (brianf-aws) [inline ml-algorithms/src/test/java/org/opensearch/ml/engine/encryptor/EncryptorImplTest.java:1]: thanks for making the tests very thorough!

**Review by brianf-aws — APPROVED** [review]
Very good changes, curious to know your thoughts on making the TTL configurable

File: ml-algorithms/src/main/java/org/opensearch/ml/engine/encryptor/EncryptorImpl.java [hunk 3]
```diff
@@ -121,13 +142,26 @@ public String generateMasterKey() {
...
         return JceMasterKey.getInstance(new SecretKeySpec(bytes, "AES"), "Custom", "", "AES/GCM/NOPADDING");
     }
 
+    private String getOrInitMasterKey(String tenantId) {
+        String masterKey = tenantMasterKeys.getIfPresent(Objects.requireNonNullElse(tenantId, DEFAULT_TENANT_ID));
+        if (masterKey != null) {
+            return masterKey;
+        }
+        initMasterKey(tenantId);
+        masterKey = tenantMasterKeys.getIfPresent(Objects.requireNonNullElse(tenantId, DEFAULT_TENANT_ID));
```
Comment (Zhangxunmt) [inline ml-algorithms/src/main/java/org/opensearch/ml/engine/encryptor/EncryptorImpl.java]: Objects.requireNonNullElse(tenantId, DEFAULT_TENANT_ID) is same called twice but can use a variable to remove the duplication. 
```
String effectiveTenantId = Objects.requireNonNullElse(tenantId, DEFAULT_TENANT_ID); 
```

File: ml-algorithms/src/main/java/org/opensearch/ml/engine/encryptor/EncryptorImpl.java [hunk 4]
```diff
@@ -121,13 +142,26 @@ public String generateMasterKey() {
...
+        byte[] bytes = Base64.getDecoder().decode(masterKey);
         return JceMasterKey.getInstance(new SecretKeySpec(bytes, "AES"), "Custom", "", "AES/GCM/NOPADDING");
     }
 
+    private String getOrInitMasterKey(String tenantId) {
+        String masterKey = tenantMasterKeys.getIfPresent(Objects.requireNonNullElse(tenantId, DEFAULT_TENANT_ID));
+        if (masterKey != null) {
+            return masterKey;
+        }
+        initMasterKey(tenantId);
```
Comment (Zhangxunmt) [inline ml-algorithms/src/main/java/org/opensearch/ml/engine/encryptor/EncryptorImpl.java]: nit: When the concurrency TPS is high, I think using the thread safe check here could avoid duplicate index writing in the initMasterKey(tenantId) to have better performance, since the MLConfigIndex writing/update is turned into sync operation in initMasterKey(tenantId). 

    synchronized (lock) {
        masterKey = tenantMasterKeys.getIfPresent(effectiveTenantId);
        if (masterKey == null) {
            initMasterKey(tenantId);
            masterKey = tenantMasterKeys.getIfPresent(effectiveTenantId);
        }
    }

File: ml-algorithms/src/main/java/org/opensearch/ml/engine/encryptor/EncryptorImpl.java [hunk 5]
```diff
@@ -62,23 +67,86 @@ public class EncryptorImpl implements Encryptor {
...
+    private final Object lock = new Object();
+    private volatile long masterKeyCacheTtlMinutes;
 
     // concurrent map can't have null as a key. This is to support single tenancy
     // assigning some random string so that it can't be duplicate
     public static final String DEFAULT_TENANT_ID = "03000200-0400-0500-0006-000700080009";
 
     public EncryptorImpl(ClusterService clusterService, Client client, SdkClient sdkClient, MLIndicesHandler mlIndicesHandler) {
-        this.tenantMasterKeys = new ConcurrentHashMap<>();
+        this.masterKeyCacheTtlMinutes = ML_COMMONS_MASTER_KEY_CACHE_TTL_MINUTES.get(clusterService.getSettings());
```
Comment (dhrubo-os) [inline ml-algorithms/src/main/java/org/opensearch/ml/engine/encryptor/EncryptorImpl.java:81]: What do you think about adding this here: https://github.com/opensearch-project/ml-commons/blob/main/common/src/main/java/org/opensearch/ml/common/settings/MLFeatureEnabledSetting.java ?

File: ml-algorithms/src/main/java/org/opensearch/ml/engine/encryptor/EncryptorImpl.java [hunk 6]
```diff
@@ -62,23 +67,86 @@ public class EncryptorImpl implements Encryptor {
...
+     * Updates the cache TTL when the cluster setting changes.
+     * Note: This only affects new cache entries. Existing entries will expire based on their original TTL.
+     */
+    private void updateCacheTtl(Integer newTtlMinutes) {
+        this.masterKeyCacheTtlMinutes = newTtlMinutes;
+        log.info("Master key cache TTL updated to {} minutes. Note: Existing cache entries retain their original TTL.", newTtlMinutes);
+    }
+
+    // Package-private constructor for testing with custom TTL
+    EncryptorImpl(
```
Comment (dhrubo-os) [inline ml-algorithms/src/main/java/org/opensearch/ml/engine/encryptor/EncryptorImpl.java:100]: [nit] can we add `@VisibleForTesting` ?

File: ml-algorithms/src/main/java/org/opensearch/ml/engine/encryptor/EncryptorImpl.java (hunk 5 above)
Comment (arjunkumargiri) [reply ml-algorithms/src/main/java/org/opensearch/ml/engine/encryptor/EncryptorImpl.java:81]: Dynamic setting for ML master key cache will not be required. It needs to be a bootstrap configuration. 

Let me know if you have concerns.

Comment (mingshl) [reply ml-algorithms/src/main/java/org/opensearch/ml/engine/encryptor/EncryptorImpl.java:81]: IMO, I don't want a B/G just because of increasing expiration time

File: ml-algorithms/src/main/java/org/opensearch/ml/engine/encryptor/EncryptorImpl.java [hunk 7]
```diff
@@ -62,23 +68,75 @@ public class EncryptorImpl implements Encryptor {
...
+
+    // Package-private constructor for testing with custom TTL
+    EncryptorImpl(String tenantId, String masterKey, long cacheTtl, TimeUnit timeUnit) {
+        this.tenantMasterKeys = CacheBuilder
+            .newBuilder()
+            .expireAfterWrite(cacheTtl, timeUnit)
+            .removalListener(new RemovalListener<String, String>() {
+                @Override
+                public void onRemoval(RemovalNotification<String, String> notification) {
+                    log.info("Master key cache entry removed - Tenant: {}, Cause: {}", notification.getKey(), notification.getCause());
```
Comment (mingshl) [inline ml-algorithms/src/main/java/org/opensearch/ml/engine/encryptor/EncryptorImpl.java:136]: is it safe to log the tenant here?

Comment (dhrubo-os) [reply ml-algorithms/src/main/java/org/opensearch/ml/engine/encryptor/EncryptorImpl.java:136]: yeah tenant id is a metadata. So this should be fine from security POV

Comment (mingshl) [reply ml-algorithms/src/main/java/org/opensearch/ml/engine/encryptor/EncryptorImpl.java:136]: all good from me then, approve.

File: ml-algorithms/src/test/java/org/opensearch/ml/engine/encryptor/EncryptorImplTest.java [hunk 8]
```diff
@@ -779,6 +793,188 @@ public void encrypt_GetSourceAsMapIsNull_ShouldThrowResourceNotFound() throws Ex
...
+        // Second encryption should use cached key (no additional DDB call)
+        String encrypted2 = encryptor.encrypt("test", TENANT_ID);
+        Assert.assertNotNull(encrypted2);
+
+        // Verify DDB (client.get) was called only once, not twice
+        verify(client, times(1)).get(any(), any());
+    }
+
+    @Test
+    public void testCacheExpiryConfiguration() throws Exception {
```
Comment (akolarkunnu) [inline ml-algorithms/src/test/java/org/opensearch/ml/engine/encryptor/EncryptorImplTest.java:831]: @arjunkumargiri What is the difference between tests testMasterKeyRefetchAfterCacheExpiry() and testCacheExpiryConfiguration(). I don't see any clear difference. Both are testing same functioanlity.

Comment (arjunkumargiri) [reply ml-algorithms/src/test/java/org/opensearch/ml/engine/encryptor/EncryptorImplTest.java:831]: It should be fine to remove it, I started testing the timeout config in testCacheExpiryConfiguration but ran into few challenges.

Comment (akolarkunnu) [reply ml-algorithms/src/test/java/org/opensearch/ml/engine/encryptor/EncryptorImplTest.java:831]: Ok, I will remove it in my PR https://github.com/opensearch-project/ml-commons/pull/3919
