### PR TITLE
Enhance Message and Memory API Validation and storage

### LINKED ISSUE #3250: [BUG] Add more validation checks for message API
**What is the bug?**

In testing the message API, 

- the message can be empty, it creates new messages with fields in null values.  
- when sending fields that is not defined in the mapping, it also creates new messages with fields in null values.  It doesn't throw exception. 

We need to add validation and throw proper exceptions. 

**How can one reproduce the bug?**
```
POST /_plugins/_ml/memory/
{
  "name": "Conversation for a RAG pipeline"
}
 

POST /_plugins/_ml/memory/-IyfjZMBQoVk1Lk93xvv/messages
{
   
}

GET /_plugins/_ml/memory/message/-YyljZMBQoVk1Lk99BtH

##returnning  new message -YyljZMBQoVk1Lk99BtH  with fields in null values.  
{
  "memory_id": "-IyfjZMBQoVk1Lk93xvv",
  "message_id": "-YyljZMBQoVk1Lk99BtH",
  "create_time": "2024-12-03T17:51:23.713738264Z",
  "input": null,
  "prompt_template": null,
  "response": null,
  "origin": null,
  "additional_info": {}
}

POST /_plugins/_ml/memory/-IyfjZMBQoVk1Lk93xvv/messages
{
   "message":{"role":"system","content":"Hi!"}
}


GET /_plugins/_ml/memory/message/giiijZMBjeltLmSpmHa5
##returnning message giiijZMBjeltLmSpmHa5  with fields in null values.  
{
  "memory_id": "-IyfjZMBQoVk1Lk93xvv",
  "message_id": "giiijZMBjeltLmSpmHa5",
  "create_time": "2024-12-03T17:47:43.667740682Z",
  "input": null,
  "prompt_template": null,
  "response": null,
  "origin": null,
  "additional_info": {}
}
```

 
**What is the expected behavior?**
throw proper exception to guide users to send in valid messages. 

**What is your host/environment?**
 - Plugins

**Do you have any screenshots?**

**Do you have any additional context?**
Add any other context about the problem.

### PR DESCRIPTION
**Pull request by rithin-pullela-aws**
Skip saving empty fields in interactions and conversations to optimize storage usage. 
Modify GET requests for interactions and conversations to return only non-null fields. 
Throw an exception if all fields in a create interaction call are empty or null. 
Add unit tests to cover the above cases.

### Description
[Describe what this change achieves]

### Related Issues
Resolves #3250

### Check List
- [ ] New functionality includes testing.
- [ ] New functionality has been documented.
- [ ] API changes companion pull request [created](https://github.com/opensearch-project/opensearch-api-specification/blob/main/DEVELOPER_GUIDE.md).
- [ ] Commits are signed per the DCO using `--signoff`.
- [ ] Public documentation issue/PR [created](https://github.com/opensearch-project/documentation-website/issues/new/choose).

By submitting this pull request, I confirm that my contribution is made under the terms of the Apache 2.0 license.
For more information on following Developer Certificate of Origin and signing off your commits, please check [here](https://github.com/opensearch-project/ml-commons/blob/main/CONTRIBUTING.md#developer-certificate-of-origin).

### CODE REVIEW

**Comment by dhrubo-os** [comment]
```

ConversationMetaIndexITTests > testCanGetAConversationById FAILED
    org.opensearch.discovery.ClusterManagerNotDiscoveredException at TransportClusterManagerNodeAction.java:345
    java.lang.AssertionError at ConversationMetaIndexITTests.java:573

File: common/src/test/java/org/opensearch/ml/common/conversation/InteractionTests.java [hunk 1]
```diff
@@ -124,13 +124,14 @@ public void test_ToXContent() throws IOException {
...
             .additionalInfo(Collections.singletonMap("suggestion", "new suggestion"))
+            .response("sample response")
             .traceNum(1)
             .build();
         XContentBuilder builder = XContentBuilder.builder(XContentType.JSON.xContent());
         interaction.toXContent(builder, EMPTY_PARAMS);
         String interactionContent = TestHelper.xContentBuilderToString(builder);
         assertEquals(
-            "{\"memory_id\":\"conversation id\",\"message_id\":null,\"create_time\":null,\"input\":null,\"prompt_template\":null,\"response\":null,\"origin\":\"amazon bedrock\",\"additional_info\":{\"suggestion\":\"new suggestion\"},\"parent_message_id\":\"parant id\",\"trace_number\":1}",
+            "{\"memory_id\":\"conversation id\",\"message_id\":null,\"create_time\":null,\"response\":\"sample response\",\"origin\":\"amazon bedrock\",\"additional_info\":{\"suggestion\":\"new suggestion\"},\"parent_message_id\":\"parant id\",\"trace_number\":1}",
```
[the remark this answers is not in the document]
Comment (rithin-pullela-aws) [reply common/src/test/java/org/opensearch/ml/common/conversation/InteractionTests.java:134]: The fields input and prompt_template are empty and the expected response of these 2 fields have been updated from null to empty response. I believe that would suffice as a check to test the expected behavior.

[the remark this answers is not in the document]
Comment (mingshl) [reply common/src/test/java/org/opensearch/ml/common/conversation/InteractionTests.java:134]: I mean you should also check `"prompt_template\":""`

File: memory/src/main/java/org/opensearch/ml/memory/action/conversation/CreateConversationRequest.java [hunk 2]
```diff
@@ -137,12 +137,27 @@ public static CreateConversationRequest fromRestRequest(RestRequest restRequest)
         }
         try (XContentParser parser = restRequest.contentParser()) {
             Map<String, Object> body = parser.map();
+            String name = null;
+            String applicationType = null;
+            Map<String, String> additionalInfo = null;
+
+            for (String key : body.keySet()) {
```
Comment (dhrubo-os) [inline memory/src/main/java/org/opensearch/ml/memory/action/conversation/CreateConversationRequest.java:144]: In a map why do we need  a loop? Can't we do:

```
// Extract fields with null safety
        String name = (String) body.getOrDefault(ActionConstants.REQUEST_CONVERSATION_NAME_FIELD, null);
        String applicationType = (String) body.getOrDefault(APPLICATION_TYPE_FIELD, null);
        Map<String, String> additionalInfo = null;

        if (body.containsKey(META_ADDITIONAL_INFO_FIELD)) {
            try {
                additionalInfo = (Map<String, String>) body.get(META_ADDITIONAL_INFO_FIELD);
            } catch (ClassCastException e) {
                throw new IllegalArgumentException("Invalid type for field [" + META_ADDITIONAL_INFO_FIELD + "]", e);
            }
        }
```

File: common/src/test/java/org/opensearch/ml/common/conversation/InteractionTests.java (hunk 1 above)
[the remark this answers is not in the document]
Comment (dhrubo-os) [reply common/src/test/java/org/opensearch/ml/common/conversation/InteractionTests.java:134]: >I mean you should also check "prompt_template\":""

```
        if (promptTemplate != null && !promptTemplate.trim().isEmpty()) {
            builder.field(ConversationalIndexConstants.INTERACTIONS_PROMPT_TEMPLATE_FIELD, promptTemplate);
        }
```

This block is not adding `prompt_template` to the XContentBuilder. So XContentBuilder doesn't have this `prompt_template` object in this test.

File: memory/src/main/java/org/opensearch/ml/memory/action/conversation/CreateConversationRequest.java (hunk 2 above)
Comment (rithin-pullela-aws) [reply memory/src/main/java/org/opensearch/ml/memory/action/conversation/CreateConversationRequest.java:144]: Essentially what I am trying to do is: if we have an unknown parameter in the request body we want to throw an error. So the default case here throws an IllegalArgumentException. So if there is an unknown field it will be caught in the loop and an exception is thrown in the default case.

With the method you suggested, we are reading the known/expected parameters but we won't be dealing with unknown/bad parameters.

File: memory/src/test/java/org/opensearch/ml/memory/action/conversation/CreateConversationRequestTests.java [hunk 3]
```diff
@@ -132,4 +133,24 @@ public void testRestRequest_WithAdditionalInfo() throws IOException {
         Assert.assertEquals("value1", request.getAdditionalInfos().get("key1"));
         Assert.assertEquals(123, request.getAdditionalInfos().get("key2"));
     }
+
+    public void testRestRequest_WithUnknownFields_Fails() throws IOException {
```
Comment (dhrubo-os) [inline memory/src/test/java/org/opensearch/ml/memory/action/conversation/CreateConversationRequestTests.java:137]:
```
@Test
public void testRestRequest_WithUnknownFields_Fails() throws IOException {
    // Arrange
    String name = "test-name";
    RestRequest req = new FakeRestRequest.Builder(NamedXContentRegistry.EMPTY)
        .withContent(
            new BytesArray(gson.toJson(Map.of(
                ActionConstants.REQUEST_CONVERSATION_NAME_FIELD, name,
                "unknown_field", "some value"
            ))),
            MediaTypeRegistry.JSON
        )
        .build();

    // Act and Assert
    OpenSearchParseException exception = assertThrows(
        OpenSearchParseException.class,
        () -> CreateConversationRequest.fromRestRequest(req),
        "Expected OpenSearchParseException due to unknown field"
    );

    // Verify exception content (optional)
    assertTrue(exception.getMessage().contains("Invalid field [unknown_field]"),
               "Exception message does not contain the expected content.");
}
```

This should work?

File: memory/src/test/java/org/opensearch/ml/memory/action/conversation/CreateInteractionRequestTests.java [hunk 4]
```diff
@@ -153,4 +154,63 @@ public void testFromRestRequest_Trace() throws IOException {
...
+                "unknown_field",
+                "some value"
+            );
+
+        RestRequest rrequest = new FakeRestRequest.Builder(NamedXContentRegistry.EMPTY)
+            .withParams(Map.of(ActionConstants.MEMORY_ID, "cid"))
+            .withContent(new BytesArray(gson.toJson(params)), MediaTypeRegistry.JSON)
+            .build();
+
+        try {
```
Comment (dhrubo-os) [inline memory/src/test/java/org/opensearch/ml/memory/action/conversation/CreateInteractionRequestTests.java:180]: Try to use assertThrows.

File: memory/src/test/java/org/opensearch/ml/memory/action/conversation/CreateConversationRequestTests.java (hunk 3 above)
Comment (rithin-pullela-aws) [reply memory/src/test/java/org/opensearch/ml/memory/action/conversation/CreateConversationRequestTests.java:137]: Will use assertThrows

File: memory/src/test/java/org/opensearch/ml/memory/action/conversation/CreateInteractionRequestTests.java (hunk 4 above)
Comment (rithin-pullela-aws) [reply memory/src/test/java/org/opensearch/ml/memory/action/conversation/CreateInteractionRequestTests.java:180]: Will use assertThrows

File: memory/src/main/java/org/opensearch/ml/memory/action/conversation/CreateConversationRequest.java (hunk 2 above)
Comment (dhrubo-os) [reply memory/src/main/java/org/opensearch/ml/memory/action/conversation/CreateConversationRequest.java:144]: Do we need to throw the exception? If we get our desired value from the request, why do we need to throw the exception? Usually we don't do that. Customer can add numerous amount of items in the payload request, but we only care for the values what we need. We just discard other values, we don't need to throw exception for that.

Comment (rithin-pullela-aws) [reply memory/src/main/java/org/opensearch/ml/memory/action/conversation/CreateConversationRequest.java:144]: I was trying to cater to this part of the [issue](https://github.com/opensearch-project/ml-commons/issues/3250#:~:text=when%20sending%20fields%20that%20is%20not%20defined%20in%20the%20mapping%2C%20it%20also%20creates%20new%20messages%20with%20fields%20in%20null%20values.%20It%20doesn%27t%20throw%20exception.)

@mingshl, would love to hear your thoughts about this.

Comment (rithin-pullela-aws) [reply memory/src/main/java/org/opensearch/ml/memory/action/conversation/CreateConversationRequest.java:144]: I personally believe throwing exceptions is the way to go. Because we can enforce a strict contract and if the customers make an unintentional mistake perhaps a typo, they can quickly realize their error and remedy right then,

File: memory/src/test/java/org/opensearch/ml/memory/action/conversation/CreateConversationRequestTests.java [hunk 5]
```diff
@@ -132,4 +133,22 @@ public void testRestRequest_WithAdditionalInfo() throws IOException {
...
+            )
+            .build();
+
+        OpenSearchParseException exception = assertThrows(
+            "Expected OpenSearchParseException due to unknown field",
+            OpenSearchParseException.class,
+            () -> CreateConversationRequest.fromRestRequest(req)
+        );
+
+        assertEquals(exception.getMessage(), "Invalid field [unknown_field] found in request body");
```
[the remark this answers is not in the document]
Comment (rithin-pullela-aws) [reply memory/src/test/java/org/opensearch/ml/memory/action/conversation/CreateConversationRequestTests.java:152]: If you look at line 141, 
```RestRequest req = new FakeRestRequest.Builder(NamedXContentRegistry.EMPTY)
            .withContent(
                new BytesArray(gson.toJson(Map.of(ActionConstants.REQUEST_CONVERSATION_NAME_FIELD, name, "unknown_field", "some value"))),
                MediaTypeRegistry.JSON
            )
            .build();```
            
The request I made has a parameter with the name "unknown_field". "unknown_field" is the key you are referring to.

File: memory/src/main/java/org/opensearch/ml/memory/index/InteractionsIndex.java [hunk 6]
```diff
@@ -153,36 +154,36 @@ public void createInteraction(
...
-                                timestamp,
-                                ConversationalIndexConstants.PARENT_INTERACTIONS_ID_FIELD,
-                                parintid,
-                                ConversationalIndexConstants.INTERACTIONS_TRACE_NUMBER_FIELD,
-                                traceNumber
-                            );
+                        Map<String, Object> sourceMap = new HashMap<>();
+                        sourceMap.put(ConversationalIndexConstants.INTERACTIONS_CONVERSATION_ID_FIELD, conversationId);
+                        sourceMap.put(ConversationalIndexConstants.INTERACTIONS_CREATE_TIME_FIELD, timestamp);
+                        sourceMap.put(ConversationalIndexConstants.PARENT_INTERACTIONS_ID_FIELD, parintid);
```
[the remark this answers is not in the document]
Comment (rithin-pullela-aws) [reply memory/src/main/java/org/opensearch/ml/memory/index/InteractionsIndex.java:168]: Yes, it should be parentId, will refactore

**Review by mingshl — APPROVED** [review]
LGTM!

File: memory/src/main/java/org/opensearch/ml/memory/action/conversation/CreateInteractionRequest.java [hunk 7]
```diff
@@ -171,6 +171,16 @@ public static CreateInteractionRequest fromRestRequest(RestRequest request) thro
...
         }
 
+        boolean allFieldsEmpty = (input == null || input.trim().isEmpty())
+            && (prompt == null || prompt.trim().isEmpty())
+            && (response == null || response.trim().isEmpty())
+            && (origin == null || origin.trim().isEmpty())
+            && (addinf == null || addinf.isEmpty());
+        if (allFieldsEmpty) {
+            throw new IllegalArgumentException(
+                "At least one of the following parameters must be non-empty: " + "input, prompt_template, response, origin, additional_info"
```
Comment (dhrubo-os) [inline memory/src/main/java/org/opensearch/ml/memory/action/conversation/CreateInteractionRequest.java:181]: Just curious to know if I just give addition info, will this feature work? Did you test?

Comment (rithin-pullela-aws) [reply memory/src/main/java/org/opensearch/ml/memory/action/conversation/CreateInteractionRequest.java:181]: Yes, I tested it manually and I also have a corresponding [unit test](https://github.com/opensearch-project/ml-commons/pull/3283/files#:~:text=public%20void%20testFromRestRequest_WithAllFieldsEmpty_Fails,%7D).

**Review by dhrubo-os — APPROVED** [review]
