### PR TITLE
Propagate stream error

### LINKED ISSUE #4749: [BUG] stream errors not propagated properly
**What is the bug?**
At the moment, when error occurs [here](https://github.com/opensearch-project/ml-commons/blame/main/plugin/src/main/java/org/opensearch/ml/rest/RestMLExecuteStreamAction.java#L282-L292) (example: when chat agent is not able to access memory service), the response sent to the user is:
```
data: {"error": "[ip-10-0-105-16.us-west-2.compute.internal][10.0.105.16:9300][cluster:admin/opensearch/ml/execute/stream]"}
```
Which is not very helpful. We should show a proper error explaining what went wrong instead.

**How can one reproduce the bug?**

**What is the expected behavior?**

**What is your host/environment?**
 - Plugins

**Do you have any screenshots?**

**Do you have any additional context?**
Add any other context about the problem.

### PR DESCRIPTION
**Pull request by jiapingzeng**
### Description
Propagate stream error. Resolves https://github.com/opensearch-project/ml-commons/issues/4749.

Tested that when there is an underlying error (e.g. agentic memory error), the error is propagated properly.
```
data: {"type":"RUN_STARTED","timestamp":1776197477955,"threadId":"6930a356-dd3b-4620-8b5f-d41512d10453","runId":"ec330a5e-e247-46e3-bc27-dd920cf2b6af"}

data: {"type":"RUN_ERROR","timestamp":1776197478098,"message":"Memory container not found"}
```

### Related Issues
Resolves https://github.com/opensearch-project/ml-commons/issues/4749

### Check List
- [x] New functionality includes testing.
- [ ] New functionality has been documented.
- [ ] API changes companion pull request [created](https://github.com/opensearch-project/opensearch-api-specification/blob/main/DEVELOPER_GUIDE.md).
- [ ] Commits are signed per the DCO using `--signoff`.
- [ ] Public documentation issue/PR [created](https://github.com/opensearch-project/documentation-website/issues/new/choose).

By submitting this pull request, I confirm that my contribution is made under the terms of the Apache 2.0 license.
For more information on following Developer Certificate of Origin and signing off your commits, please check [here](https://github.com/opensearch-project/ml-commons/blob/main/CONTRIBUTING.md#developer-certificate-of-origin).

### CODE REVIEW

File: plugin/src/test/java/org/opensearch/ml/rest/RestMLExecuteStreamActionTests.java [hunk 1]
```diff
@@ -759,6 +759,118 @@ public void testConvertToHttpChunk_errorResponse() throws Exception {
...
+    public void testBuildStreamErrorChunk_nonAGUI_opensearchStatusException() {
+        OpenSearchStatusException rootCause = new OpenSearchStatusException("Memory container not found", RestStatus.NOT_FOUND);
+        RuntimeException wrapper = new RuntimeException(rootCause);
+
+        HttpChunk chunk = restAction.buildStreamErrorChunk(wrapper, false);
+
+        assertNotNull(chunk);
+        assertTrue(chunk.isLast());
+        String content = new String(BytesReference.toBytes(chunk.content()));
+        assertTrue(content.contains("Memory container not found"));
```
Comment (mingshl) [inline plugin/src/test/java/org/opensearch/ml/rest/RestMLExecuteStreamActionTests.java:774]: nice to surface the exception message then it's easier for debugging

**Review by mingshl — APPROVED** [review]

**Comment by mingshl** [comment]
find out the version number that you would like to backport to, i can help added the backport label,

**Comment by jiapingzeng** [comment]
Thanks. Don't need to backport this change, I will cherry-pick to managed service.
